### PR TITLE
Fixed issue with style.filter attr.

### PR DESCRIPTION
**Pull request by annenkov**
Fixes for Issue #8

### CODE REVIEW

**Comment by gastonrobledo-santex** [comment]
Have you tested it in IE, Chrome or Firefox browser?

**Comment by annenkov** [comment]
I have tested it in Chrome and Firefox.
Haven't  tested in IE, because project where I use cropzoom doesn't support IE.

**Comment by gastonrobledo** [comment]
But the thing is that "progid:DXImageTransform." only applies to IE
browsers!

2013/12/19 annenkov notifications@github.com

> I have tested it in Chrome and Firefox.
> Haven't tested in IE, because project where I use cropzoom doesn't support
> IE.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cropzoom/cropzoom/pull/14#issuecomment-30924013
> .

## 

_Robledo, Gaston_

_http://about.me/gastonrobledo http://about.me/gastonrobledo *MCE 5
Platinum, C# Senior Developer,
PHP Senior Developer.
JavaScript/jQuery Senior Developer.
*CUIT_: _20-29713599-7_.
_Tel_: _+54 351 153724958_.

**Comment by annenkov** [comment]
The issue is not in progid:DXImageTransform. $image is wrapped by jQuery and 'style' attr cannot be accessed directly, but DOM object $image[0] has 'style' attr. Without this fix we cannot even test does 'progid:DXImageTransform' works or no.

**Comment by gastonrobledo-santex** [comment]
yes make sense, I forgot that is wrapped by jQuery now, it wasn't before!

+1

**Pull request merged**
