### PR TITLE
min width and height options for crop selector

### PR DESCRIPTION
**Pull request by gureedo**

### CODE REVIEW

**Comment by gastonrobledo** [comment]
Where are you using these options?

**Comment by gureedo** [comment]
Current options w and h are good for defining initial position of selector, but they also will be a minimum possoble size of it. There is no way to set initial size of selector and it minimal size.

**Comment by gastonrobledo** [comment]
I know that, what I mean is in which part of the code do you use the
min-width and min-height?

**Comment by gureedo** [comment]
I'm filling minWidth and minHeight with own values to something greater than 1x1 square.
I don't think that my use case really matters.

**Comment by gastonrobledo** [comment]
I saw that you add the two options, but I didn't see where you apply them
to the selector...

**Comment by gastonrobledo** [comment]
Sorry i saw IT now!!!!

**Pull request merged**
